enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: 'https://unpkg.com/yarn-plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
