version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    env_file:
      - .env

volumes:
  postgres_db:
